<div class="container">
    <div class="row clearfix">
        <div class="col-md-4 column">
            <form role="form" action="/signup" method="post">
                <div class="form-group">
                    <label for="exampleInputName1">Name</label>
                    <input type="text" class="form-control" id="exampleInputName1" name="name" />
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" name="email" />
                </div>
                <div class="form-group">
                    <label for="exampleInputPass1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPass1" name="password" />
                </div>

                <?php if (!empty($errors)) {
                    foreach ($errors as $error) {
                        ?>
                        <div class="error-container" style="margin: 20px auto">
                            <?php echo $error; ?>
                        </div>
                    <?php } ?>
                <?php } ?>

                <div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
