<div class="container">
<div class="row clearfix">
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"><span
                    class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                    class="icon-bar"></span><span class="icon-bar"></span></button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="#">Link</a>
                </li>
                <li>
                    <a href="#">Link</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong
                            class="caret"></strong></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Action</a>
                        </li>
                        <li>
                            <a href="#">Another action</a>
                        </li>
                        <li>
                            <a href="#">Something else here</a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="#">Separated link</a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="#">One more separated link</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <?php if ($this->session->has("user-name")) { ?>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">Profile</a>
                    </li>
                    <li>
                        <a href="/auth/logout">Logout</a>
                    </li>
                </ul>

            <?php } else { ?>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/auth">Sing In</a>
                    </li>
                    <li>
                        <a href="/signup">Register</a>
                    </li>
                </ul>

            <?php } ?>


        </div>

    </nav>
    <div class="col-md-12 column">
        <div class="page-header">
            <h1>
                Example page header
                <small>Subtext for header</small>
            </h1>
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-md-12 column">
        <div class="carousel slide" id="carousel-998813">
            <ol class="carousel-indicators">
                <li class="active" data-slide-to="0" data-target="#carousel-998813">
                </li>
                <li data-slide-to="1" data-target="#carousel-998813">
                </li>
                <li data-slide-to="2" data-target="#carousel-998813">
                </li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img alt="" src="http://lorempixel.com/1600/500/sports/1"/>

                    <div class="carousel-caption">
                        <h4>
                            First Thumbnail label
                        </h4>

                        <p>
                            Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="http://lorempixel.com/1600/500/sports/2"/>

                    <div class="carousel-caption">
                        <h4>
                            Second Thumbnail label
                        </h4>

                        <p>
                            Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="http://lorempixel.com/1600/500/sports/3"/>

                    <div class="carousel-caption">
                        <h4>
                            Third Thumbnail label
                        </h4>

                        <p>
                            Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                        </p>
                    </div>
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-998813" data-slide="prev"><span
                    class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control"
                                                                            href="#carousel-998813"
                                                                            data-slide="next"><span
                    class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="thumbnail">
                    <img alt="300x200" src="http://lorempixel.com/600/200/people"/>

                    <div class="caption">
                        <h3>
                            Thumbnail label
                        </h3>

                        <p>
                            Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                        </p>

                        <p>
                            <a class="btn btn-primary" href="/article">To comments</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumbnail">
                    <img alt="300x200" src="http://lorempixel.com/600/200/city"/>

                    <div class="caption">
                        <h3>
                            Thumbnail label
                        </h3>

                        <p>
                            Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                        </p>

                        <p>
                            <a class="btn btn-primary" href="/article">To comments</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumbnail">
                    <img alt="300x200" src="http://lorempixel.com/600/200/sports"/>

                    <div class="caption">
                        <h3>
                            Thumbnail label
                        </h3>

                        <p>
                            Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                        </p>

                        <p>
                            <a class="btn btn-primary" href="/article">To comments</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <blockquote>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                <small>Someone famous <cite>Source Title</cite></small>
            </blockquote>
        </div>
    </div>
</div>
</div>