<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <h3>
                h3. Lorem ipsum dolor sit amet.
            </h3>
            <blockquote>
                <p>
                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at
                    eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac
                    facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor
                    id nibh ultricies vehicula ut id elit.
                </p>
                <small>Someone famous <cite>Source Title</cite></small>
            </blockquote>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 column">


            <div id="comments">

                <?php

                if (!empty($comments)) {
                    foreach ($comments as $comment) {
                        ?>

                    <div><? echo $comment->getComment(); ?></div>

                    <?php
                    }
                }?>

            </div>

            <?php if ($this->session->has("user-name")) { ?>

                <div id="add-comment">
                    <form role="form" action="/article/index" method="post">
                        <div class="form-group">
                            <label for="exampleInputComment">Input your comment here:</label>
                            <textarea class="form-control" name="comment" id="exampleInputComment"></textarea>
                        </div>

                        <?php if (!empty($errors)) {
                            foreach ($errors as $error) {
                                ?>
                                <div class="error-container" style="margin: 20px auto">
                                    <?php echo $error; ?>
                                </div>
                            <?php } ?>
                        <?php } ?>

                        <div>
                            <button type="submit" class="btn btn-default">Add</button>
                        </div>
                    </form>
                </div>

            <?php } ?>

        </div>
    </div>
</div>