<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <h3>
                h3. Lorem ipsum dolor sit amet.
            </h3>
            <blockquote>
                <p>
                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at
                    eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac
                    facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor
                    id nibh ultricies vehicula ut id elit.
                </p>
                <small>Someone famous <cite>Source Title</cite></small>
            </blockquote>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 column">

            <div id="comments"></div>

            <?php if ($this->session->has("user-name")) { ?>

            <div id="add-comment">

                <textarea name="comment" id="comment" cols="130" rows="5"></textarea>
                <button style="display: block">Add</button>

            </div>

            <?php } ?>
        </div>
    </div>
</div>