<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <h3>
                h3. Lorem ipsum dolor sit amet.
            </h3>
            <blockquote>
                <p>
                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at
                    eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac
                    facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor
                    id nibh ultricies vehicula ut id elit.
                </p>
                <small>Someone famous <cite>Source Title</cite></small>
            </blockquote>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 column">


            <div id="comments">

                <?php
                $comments = Comments::find();

                foreach ($comments as $comment) {
                    ?>

                    <div><?php echo $comment->comment; ?></div>

                <?php } ?>

            </div>

            <?php if ($this->session->has("user-name")) { ?>

                <div id="add-comment">
                    <form role="form" action="/article/addcomment" method="post">
                        <div class="form-group">
                            <label for="exampleInputComment">Input your comment here:</label>
                            <textarea class="form-control" name="comment" id="exampleInputComment" cols="130"
                                      rows="5"></textarea>
                        </div>
                        <div>
                            <button type="submit" class="btn btn-default">Add</button>
                        </div>
                    </form>
                </div>

            <?php } ?>
        </div>
    </div>
</div>