<!DOCTYPE html>
<html>
	<head>
		<title>Phalcon PHP Framework</title>
        <?php
        echo $this->tag->stylesheetLink("css/bootstrap.min.css");
        echo $this->tag->stylesheetLink("css/bootstrap-theme.min.css");
        echo $this->tag->stylesheetLink("css/styles.css");

        echo $this->tag->javascriptInclude("js/jquery.min.js");
        echo $this->tag->javascriptInclude("js/bootstrap.min.js");
        ?>
	</head>
	<body>
		<?php echo $this->getContent(); ?>
	</body>
</html>